### PR TITLE
Merge aesthetics-and-bonus-features

### LINKED ISSUE #51: Create buttons to Reset
- [ ] Create "Play Again" button  that resets the fortune teller after the user has seen its fortune. This should reset the fortune teller back to its initial state (closed)
- [ ] Create "Reset Fortunes" button that resets all 8 fortunes back to its' presets.

### LINKED ISSUE #54: Add some background for the app
- [ ] Figure out what sort of background to use (pastel, patterns, something else?)
- [ ] Implement this in CSS

### LINKED ISSUE #55: Make all fonts the same
Decide which font to use and change all text to use the same font

### LINKED ISSUE #56: Implement a max character for user input
Done to prevent the flaps from showing like a whole paragraph or something

### LINKED ISSUE #63: Remove fortune input box while animating
If you edit a fortune, but do not click save and instead clicked a flap on the fortune, the input box stays on the screen. The input box should never be on the screen while after user has clicked a flap. No need to worry about saving here as fortunes save on a flap click.

### LINKED ISSUE #71: Implement line wrapping for fortune bar entries
> @AlbertXDing has limited character input to 35 characters, is there a way so that if u input 35 characters on the sidebar button, that the text creates a new line, instead of going out of the box, essentially adding to the issue. All text input should stay in the button box area.

_Originally posted by @adarsh249 in https://github.com/cse110-sp23-group1/Origami-Fortune-Teller/issues/57#issuecomment-1577194725_

### LINKED ISSUE #77: Change locations of SVG and Reset Button
Currently, SVG is blocking bottom bar and reset fortunes button is taking up too much space. Reset button should be a lil smaller and go between the SVG and the bottom bar, svg should be moved up. Nothing should be on top of each other.

### LINKED ISSUE #80: User Ease on Buttons
With the new bottom bar, we need to address a few issues.
- [ ] When the user clicks a sidebar button to edit their input, the reset button should disappear and the fortune teller svg should not be clickable. (This will help prevent accidental clicks that may reset the fortunes or start the fortune teller)
- [ ] When the user is done editing their input, the svg should be clickable again and the reset button should reappear.

I don't think these are hard to implement, but I cannot figure these out lol. Assigning CSS legends to these.

### LINKED ISSUE #84: 8-Opened not visible
If you click on flap 8, the origami disappears.

### PR DESCRIPTION
**Pull request by phentos**
Fixes #63 per @AlbertXDing

### CODE REVIEW

**Comment by AlbertXDing** [comment]
Also closes #56 #51.

**Comment by zsiyed** [comment]
Fixes #84

**Comment by adarsh249** [comment]
background is temporary, will be changed to same background with vignette style as soon as new one is created.

**Comment by christiansulaiman** [comment]
LGTM, ok to merge once Parth approves.

**Review by christiansulaiman — DISMISSED** [review]
Code looks good to me

**Pull request merged**
